// @vitest-environment node
import { afterEach, describe, expect, it, vi } from 'vitest'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { FileSystemAssetStorage } from './assets'
import { InMemoryServerRepository } from './repository'
import { OpenAIImageAssetGenerator } from './imageGeneration'

const roots: string[] = []
afterEach(async () => Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))))

describe('server image generation', () => {
  it('stores verified generated bytes and returns only a content-addressed reference', async () => {
    const root = await mkdtemp(join(tmpdir(), 'forage-image-generation-'))
    roots.push(root)
    const repository = new InMemoryServerRepository()
    const bootstrap = await repository.bootstrapOwner('owner@test.invalid')
    const principal = await repository.authenticate(bootstrap.deviceToken, 'agents:execute')
    const bytes = Buffer.from('RIFF\u0004\u0000\u0000\u0000WEBP', 'binary')
    const base64 = bytes.toString('base64')
    const fetch = vi.fn<typeof globalThis.fetch>(async () => new Response(JSON.stringify({ data: [{ b64_json: base64 }] }), { status: 200 }))
    const generator = new OpenAIImageAssetGenerator({
      repository, storage: new FileSystemAssetStorage(root), principal,
      credential: { provider: 'openai', apiKey: 'sk-secret-value' }, fetch,
    })

    const result = await generator.generate('An illustrated otter', new AbortController().signal)
    expect(result.assetId).toMatch(/^[a-f0-9]{64}$/)
    expect(JSON.stringify(result)).not.toContain(base64)
    await expect(repository.asset(principal, result.assetId)).resolves.toMatchObject({ completed: true, mediaType: 'image/webp' })
    expect(fetch).toHaveBeenCalledWith('https://api.openai.com/v1/images/generations', expect.objectContaining({
      headers: expect.objectContaining({ authorization: 'Bearer sk-secret-value' }),
    }))
  })

  it('does not pretend ChatGPT OAuth can authorize the billed Images API', async () => {
    const repository = new InMemoryServerRepository()
    const bootstrap = await repository.bootstrapOwner('owner@test.invalid')
    const principal = await repository.authenticate(bootstrap.deviceToken, 'agents:execute')
    const generator = new OpenAIImageAssetGenerator({
      repository, storage: new FileSystemAssetStorage('/unused'), principal,
      credential: { provider: 'openai-codex', accessToken: 'oauth', accountId: 'account', expiresAt: '2030-01-01T00:00:00Z' },
    })
    await expect(generator.generate('An otter', new AbortController().signal)).rejects.toThrow(/API key/i)
  })
})
