#!/bin/zsh

set -euo pipefail
setopt extended_glob
umask 077

readonly script_directory="${0:A:h}"
server_root="${script_directory}/../../.."
server_root="${server_root:A}"
readonly server_root
readonly environment_directory="${HOME}/.config/forage-server"
readonly environment_file="${environment_directory}/server.env"
readonly asset_directory_default="${HOME}/.local/share/forage-server/assets"
readonly launch_agent_directory="${HOME}/Library/LaunchAgents"
readonly launch_agent_file="${launch_agent_directory}/com.forage.server.plist"
readonly log_directory="${HOME}/Library/Logs/Forage Server"
readonly service_target="gui/$(id -u)/com.forage.server"

log() {
  print -r -- "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

fail() {
  print -u2 -r -- "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*"
  exit 1
}

prompt_default() {
  local label="$1"
  local default_value="$2"
  local answer
  read "answer?${label} [${default_value}]: "
  REPLY="${answer:-${default_value}}"
}

confirm() {
  local label="$1"
  local answer
  read "answer?${label} [Y/n]: "
  [[ -z "${answer}" || "${answer:l}" == "y" || "${answer:l}" == "yes" ]]
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command is unavailable: $1"
}

validate_port() {
  local value="$1"
  [[ "${value}" == <1-65535> ]] || fail "Port must be an integer from 1 through 65535: ${value}"
}

environment_value() {
  local value="$1"
  [[ "${value}" != *$'\n'* && "${value}" != *"'"* ]] \
    || fail "Environment values cannot contain a newline or single quote."
  print -r -- "'${value}'"
}

xml_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  print -r -- "${value}"
}

create_environment() {
  local instance_id api_port postgres_port asset_directory
  local postgres_password encryption_key temporary_file

  prompt_default "Stable server instance ID" "home-server"
  instance_id="${REPLY}"
  [[ "${instance_id}" == [A-Za-z0-9._-]## && ${#instance_id} -le 128 ]] \
    || fail "Instance ID may contain only letters, numbers, dots, underscores, and hyphens."

  prompt_default "API port" "3220"
  api_port="${REPLY}"
  validate_port "${api_port}"

  prompt_default "PostgreSQL port" "55438"
  postgres_port="${REPLY}"
  validate_port "${postgres_port}"

  prompt_default "Asset directory" "${asset_directory_default}"
  asset_directory="${REPLY}"

  postgres_password="$(openssl rand -hex 32)"
  encryption_key="1:$(openssl rand -base64 32 | tr -d '\n')"
  temporary_file="${environment_directory}/.server.env.$$.tmp"

  {
    print -r -- "# Generated by ops/macos/server/install.zsh. Keep this file private."
    print -r -- "POSTGRES_PASSWORD=$(environment_value "${postgres_password}")"
    print -r -- "POSTGRES_USER='forage_server'"
    print -r -- "POSTGRES_DB='forage_server'"
    print -r -- "POSTGRES_PORT=$(environment_value "${postgres_port}")"
    print -r -- "DATABASE_URL=$(environment_value "postgres://forage_server:${postgres_password}@127.0.0.1:${postgres_port}/forage_server")"
    print -r -- "FORAGE_INSTANCE_ID=$(environment_value "${instance_id}")"
    print -r -- "FORAGE_HOST='127.0.0.1'"
    print -r -- "FORAGE_PORT=$(environment_value "${api_port}")"
    print -r -- "FORAGE_ASSET_DIR=$(environment_value "${asset_directory}")"
    print -r -- "FORAGE_OWNER_EMAIL='owner@forage.invalid'"
    print -r -- "FORAGE_AGENT_ENCRYPTION_KEY=$(environment_value "${encryption_key}")"
    print -r -- "LOG_LEVEL='info'"
  } > "${temporary_file}"

  chmod 600 "${temporary_file}"
  mv "${temporary_file}" "${environment_file}"
  log "Created ${environment_file}; generated secrets were not printed."
}

load_environment() {
  set -a
  source "${environment_file}"
  set +a

  [[ -n "${DATABASE_URL:-}" ]] || fail "DATABASE_URL is missing from ${environment_file}."
  [[ -n "${POSTGRES_PASSWORD:-}" ]] || fail "POSTGRES_PASSWORD is missing from ${environment_file}."
  [[ -n "${POSTGRES_USER:-}" ]] || fail "POSTGRES_USER is missing from ${environment_file}."
  [[ -n "${POSTGRES_DB:-}" ]] || fail "POSTGRES_DB is missing from ${environment_file}."
  [[ -n "${FORAGE_INSTANCE_ID:-}" ]] || fail "FORAGE_INSTANCE_ID is missing from ${environment_file}."
  [[ -n "${FORAGE_PORT:-}" ]] || fail "FORAGE_PORT is missing from ${environment_file}."
  [[ -n "${FORAGE_ASSET_DIR:-}" ]] || fail "FORAGE_ASSET_DIR is missing from ${environment_file}."
  [[ -n "${FORAGE_OWNER_EMAIL:-}" ]] || fail "FORAGE_OWNER_EMAIL is missing from ${environment_file}."
  [[ -n "${FORAGE_AGENT_ENCRYPTION_KEY:-}" ]] \
    || fail "FORAGE_AGENT_ENCRYPTION_KEY is missing from ${environment_file}."

  [[ "${POSTGRES_PASSWORD}" != replace_with_* && "${FORAGE_AGENT_ENCRYPTION_KEY}" != *replace_with_* ]] \
    || fail "${environment_file} still contains template secrets. Move it aside and run this installer again."
}

install_podman() {
  command -v podman >/dev/null 2>&1 && return
  command -v brew >/dev/null 2>&1 \
    || fail "Podman is not installed and Homebrew is unavailable. Install Podman and rerun this installer."
  if confirm "Podman is not installed. Install it with Homebrew?"; then
    log "Installing Podman with Homebrew."
    brew install podman
  else
    fail "Podman is required to run the isolated PostgreSQL service."
  fi
}

start_podman() {
  local machine_names machine_name start_output

  if podman info >/dev/null 2>&1; then
    log "Podman is running."
    return
  fi

  machine_names="$(podman machine list --format '{{.Name}}' 2>/dev/null || true)"
  if [[ -z "${machine_names}" ]]; then
    log "Initializing the Podman virtual machine."
    podman machine init
    machine_names="$(podman machine list --format '{{.Name}}')"
  fi
  machine_name="${machine_names%%$'\n'*}"
  machine_name="${machine_name%%[[:space:]]##}"
  machine_name="${machine_name%\*}"
  [[ -n "${machine_name}" ]] || fail "Podman did not report a usable machine name."
  log "Starting Podman machine ${machine_name}."
  if ! start_output="$(podman machine start "${machine_name}" 2>&1)"; then
    if [[ "${start_output:l}" != *"already running"* ]]; then
      print -u2 -r -- "${start_output}"
      fail "Could not start Podman machine ${machine_name}."
    fi
  fi
  [[ -z "${start_output}" ]] || print -r -- "${start_output}"

  for attempt in {1..24}; do
    if podman info >/dev/null 2>&1; then
      log "Podman is ready."
      return
    fi
    (( attempt % 4 == 0 )) && log "Waiting for the Podman machine..."
    sleep 5
  done
  fail "Podman did not become ready within two minutes."
}

ensure_compose_provider() {
  podman compose version >/dev/null 2>&1 && return
  command -v brew >/dev/null 2>&1 \
    || fail "Podman's Compose provider is unavailable. Install podman-compose and rerun this installer."
  if confirm "Podman's Compose provider is unavailable. Install podman-compose with Homebrew?"; then
    log "Installing podman-compose with Homebrew."
    brew install podman-compose
  else
    fail "A Podman Compose provider is required."
  fi
  podman compose version >/dev/null 2>&1 \
    || fail "Podman still cannot find a Compose provider after installation."
}

unload_launch_agent() {
  if launchctl print "${service_target}" >/dev/null 2>&1; then
    log "Stopping the existing Forage server service before migration."
    launchctl bootout "${service_target}"
  fi
}

install_launch_agent() {
  local template plist service_path node_directory pnpm_directory podman_directory

  template="$(<"${script_directory}/com.forage.server.plist.template")"
  node_directory="$(dirname "$(command -v node)")"
  pnpm_directory="$(dirname "$(command -v pnpm)")"
  podman_directory="$(dirname "$(command -v podman)")"
  service_path="${node_directory}:${pnpm_directory}:${podman_directory}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

  plist="${template//__FORAGE_HOME__/$(xml_escape "${HOME}")}"
  plist="${plist//__FORAGE_SERVER_ROOT__/$(xml_escape "${server_root}")}"
  plist="${plist//__FORAGE_SERVER_ENV_FILE__/$(xml_escape "${environment_file}")}"
  plist="${plist//__FORAGE_LOG_DIR__/$(xml_escape "${log_directory}")}"
  plist="${plist//__FORAGE_SERVICE_PATH__/$(xml_escape "${service_path}")}"

  print -r -- "${plist}" > "${launch_agent_file}"
  chmod 600 "${launch_agent_file}"
  plutil -lint "${launch_agent_file}" >/dev/null

  log "Loading the Forage server service."
  launchctl bootstrap "gui/$(id -u)" "${launch_agent_file}"
}

wait_for_server() {
  local origin="http://127.0.0.1:${FORAGE_PORT}"
  log "Waiting for ${origin}/health/ready."
  for attempt in {1..30}; do
    if curl --fail --silent "${origin}/health/ready" >/dev/null 2>&1; then
      log "Forage server is ready at ${origin}."
      return
    fi
    sleep 2
  done

  print -u2 "The service was installed but did not become ready. Recent errors:"
  tail -n 40 "${log_directory}/stderr.log" 2>/dev/null || true
  fail "Inspect the service with: launchctl print ${service_target}"
}

[[ "$(uname -s)" == "Darwin" ]] || fail "This installer supports macOS only."
[[ -f "${server_root}/compose.server.yaml" ]] || fail "Could not find compose.server.yaml under ${server_root}."
[[ -f "${server_root}/apps/server/package.json" ]] || fail "Run this installer from a complete Forage checkout."

for command_name in node openssl plutil pnpm curl launchctl; do
  require_command "${command_name}"
done
install_podman
require_command podman

log "Installing the Forage server service from ${server_root}."
mkdir -p "${environment_directory}" "${launch_agent_directory}" "${log_directory}"

if [[ -f "${environment_file}" ]]; then
  chmod 600 "${environment_file}"
  log "Reusing the existing environment at ${environment_file}."
else
  create_environment
fi
load_environment
mkdir -p "${FORAGE_ASSET_DIR}"

if [[ ! -x "${server_root}/node_modules/.bin/tsx" ]]; then
  if confirm "Dependencies are not installed. Run pnpm install --frozen-lockfile?"; then
    log "Installing locked workspace dependencies."
    pnpm --dir "${server_root}" install --frozen-lockfile
  else
    fail "Install dependencies before running the server."
  fi
fi

unload_launch_agent
start_podman
ensure_compose_provider
compose_command=(podman compose --env-file "${environment_file}" --file "${server_root}/compose.server.yaml")

log "Starting the isolated PostgreSQL service."
"${compose_command[@]}" up -d --wait

log "Applying database migrations."
(
  cd "${server_root}"
  pnpm --filter @forage/server db:migrate
)

owner_count="$("${compose_command[@]}" exec -T postgres \
  psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -Atc 'SELECT count(*) FROM owners')"
owner_count="${owner_count//[[:space:]]/}"
[[ "${owner_count}" == <0-> ]] || fail "Could not determine whether the server has an owner."

if (( owner_count == 0 )); then
  log "Bootstrapping the owner. The following credentials are displayed only once; save them now."
  (
    cd "${server_root}"
    pnpm --filter @forage/server bootstrap
  )
else
  log "The database is already bootstrapped; no new credentials were created."
fi

install_launch_agent
wait_for_server

log "Installation complete."
print -r -- ""
print -r -- "Connect the desktop to http://127.0.0.1:${FORAGE_PORT} using the bootstrap device token."
print -r -- "Service status: launchctl print ${service_target}"
print -r -- "Service errors: tail -f '${log_directory}/stderr.log'"
